### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by byanko55**
**New Features**
* Remove Jquery dependency

**Minor Updates**
* Compress css/js resources
* Home title hover effect

**Bug Fixes**
* Unwanted indent from 2nd~3rd lines of related posts
* Vertical margin of tag items is not set
* Browser tab show page title as `Index`

### CODE REVIEW

**Comment by cvlian** [comment]
I recommended you NOT to push the gem build before closing the PR. Didn't I say so?

**Comment by cvlian** [comment]
Minifying css/js is cool, but it could be more critical to reduce script evaluation time. See how much portion it takes for the total rendering time. [Lighthouse](https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=ko) will be helpful.

**Review by mgarrixx — COMMENTED** [review]
Changing profile_img attribute in _config.yml doesn’t work

**Comment by cvlian** [comment]
I think we have lots of things are still left unpatched. Check them all and make another PR later.

**Pull request closed without merging**
